services:
  - type: web
    name: q-safe-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
